apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{.Values.namespace}}
#type: kubernetes.io/basic-auth
data:
  POSTGRES_PASSWORD: {{ .Files.Get "secrets/postgres-password.txt" | b64enc | quote }}
  POSTGRES_USER: {{ .Files.Get "secrets/postgres-username.txt" | b64enc | quote }}
  POSTGRES_DB: {{ .Files.Get "secrets/postgres-database.txt" | b64enc | quote }}
  POSTGRES_HOST: {{ .Files.Get "secrets/postgres-host.txt" | b64enc | quote }}
  POSTGRES_PORT: {{ .Files.Get "secrets/postgres-port.txt" | b64enc }}





