
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-test-auth
  namespace: {{.Values.namespace}}
type: kubernetes.io/basic-auth	
stringData:
  username: {{.Files.Get "secrets/app-test-username.txt"|quote}}
  password: {{.Files.Get "secrets/app-test-password.txt"|quote}}
  #serveur: {{.Files.Get "secrets/app-test-server.txt"|quote}}
 

  


